### ISSUE TITLE
NETStandard.WindowsCE 1.8.0 can't work on WindowsCE with .NET CF 3.5

### ISSUE THREAD

**Issue by andot** [WindowsCE/NETStandard.WindowsCE#51]
![image](https://user-images.githubusercontent.com/232161/76155187-85842100-6123-11ea-85a9-e7a5224d2b27.png)

NETStandard.WindowsCE 1.7.1 works, but 1.8.0 can't work.

**Comment by skarllot** [comment]
Fixed at 1.8.1 release.
