### ISSUE TITLE
was any update for Windows CE OS

### ISSUE THREAD

**Issue by sgf** [WindowsCE/NETStandard.WindowsCE#52]
my mean is OS.
Because Microsoft gave up Windows CE system update and support. The .net is crumbling in handheld devices. Android began to enter in large numbers, and java and kotlin began to eat market share. After all this is completely switched, what else can we do with .net?

**Comment by skarllot** [comment]
Windows CE was deprecated a long time ago and I recently gave up on maintaining this port.

**Comment by sgf** [comment]
> Windows CE was deprecated a long time ago and I recently gave up on maintaining this port. But anyone is welcome to submit PRs.

Windows CE  is not open source,the Communities can do any more about it
